#!/bin/bash

set -e

kill_server () {
  ps -e --format pid,command | grep 'mkdocs' | grep -v 'grep' | awk '{ print $1 }' | xargs -r kill -KILL;
}

# Runs from the project root directory.
# It is assumed that the pages are already built.

if [[ "$1x" == "killx" ]]; then
  kill_server;
  exit 0;
fi

# Root directory of the project
ROOT_DIR=.
# Directory for source Markdown files
SRC_DIR="$ROOT_DIR/src"
# Directory with the site files generated by mkdocs
SITE_DIR="$ROOT_DIR/site"
# Directory with linter binaries
BIN_DIR=~/.local/bin
# Directory with configurations
CFG_DIR="$ROOT_DIR/misc"

# 1. Lint Markdown files
$BIN_DIR/mdl --style "$CFG_DIR/markdownlintrc" "$SRC_DIR"
# 2. Lint generated HTML pages
$BIN_DIR/html5validator --root "$SITE_DIR" --show-warnings
# 3. Lint links
kill_server
python -m mkdocs serve &
sleep 10
$BIN_DIR/linkchecker -f "$CFG_DIR/linkcheckerrc" http://localhost:8000/
kill_server
